GET http://localhost:3001/

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Rocky Mountains",
    "author": "John Cena",
    "url": "google.com",
    "likes": "20"
}

###
GET http://localhost:3001/api/blogs

###
DELETE http://localhost:3001/api/blogs/632e5b542273cdfae6491c03